site_name: Ukrainian IT Communities
repo_url: https://github.com/nikit0ns/Ukrainian_IT_Communities
repo_name: nikit0ns/Ukrainian_IT_Communities
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nikit0ns
    - icon: fontawesome/brands/telegram
      link: https://t.me/nikit0ns
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NikitaKasanenk1
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/nikitons_/
  analytics:
    provider: google
    property: G-KWT5DEYZWX 
    feedback:
      title: Чи була ця сторінка корисною?
      ratings:
        - icon: material/thumb-up-outline
          name: Ця сторінка була корисною
          data: 1
          note: >-
            Дякуємо за ваш відгук!
        - icon: material/thumb-down-outline
          name: Цю сторінку можна покращити
          data: 0
          note:
            Дякуємо за ваш відгук! Допоможіть нам покращити цю сторінку, скориставшись <a href="https://docs.google.com/forms/d/e/1FAIpQLSfCAJxbTuu43ezWul416gSV4SpZFYriK8sF__Qfemz_UZZ_pg/viewform" target="_blank" rel="noopener">формою зворотного зв'язку</a>.  

copyright: Copyright &copy; 2023-2024 Nikita Kasyanenko
